{"@timestamp":"2025-03-09T10:20:37.3069062Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T10:20:37.4844711Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"Starting BotApplicationTests using Java 23.0.2 with PID 14732 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T10:20:37.4869266Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T10:20:41.114157Z","logger_name":"org.testcontainers.images.PullPolicy","thread_name":"main","message":"Image pull policy will be performed by: DefaultPullPolicy()"}
{"@timestamp":"2025-03-09T10:20:41.1214886Z","logger_name":"org.testcontainers.utility.ImageNameSubstitutor","thread_name":"main","message":"Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')"}
{"@timestamp":"2025-03-09T10:20:41.26852Z","logger_name":"org.testcontainers.DockerClientFactory","thread_name":"main","message":"Testcontainers version: 1.20.4"}
{"@timestamp":"2025-03-09T10:20:41.991329Z","logger_name":"org.testcontainers.dockerclient.DockerMachineClientProviderStrategy","thread_name":"main","message":"docker-machine executable was not found on PATH ([C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common, C:\\ProgramData\\Oracle\\Java\\javapath, C:\\WINDOWS\\system32, C:\\WINDOWS, C:\\WINDOWS\\System32\\Wbem, C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\, C:\\WINDOWS\\System32\\OpenSSH\\, C:\\Program Files\\dotnet\\, C:\\Program Files (x86)\\dotnet\\, C:\\Program Files\\Git\\cmd, C:\\Program Files (x86)\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\DTS\\Binn\\, C:\\Program Files\\Docker\\Docker\\resources\\bin, C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\, C:\\Program Files\\CMake\\bin, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\, C:\\Users\\Andrew\\AppData\\Local\\Microsoft\\WindowsApps, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Microsoft VS Code\\bin, C:\\msys64\\ucrt64\\bin, C:\\Users\\Andrew\\AppData\\Local\\GitHubDesktop\\bin, C:\\Users\\Andrew\\.dotnet\\tools])"}
{"@timestamp":"2025-03-09T10:20:41.99234Z","logger_name":"org.testcontainers.dockerclient.DockerClientProviderStrategy","thread_name":"main","message":"Could not find a valid Docker environment. Please check configuration. Attempted configurations were:\nAs no valid configuration was found, execution cannot continue.\nSee https://java.testcontainers.org/on_failure.html for more details."}
{"@timestamp":"2025-03-09T10:20:41.9943425Z","logger_name":"org.springframework.web.context.support.GenericWebApplicationContext","thread_name":"main","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Error creating bean with name 'redisContainer' defined in class path resource [backend/academy/bot/TestcontainersConfiguration.class]: Could not find a valid Docker environment. Please see logs and check configuration"}
{"@timestamp":"2025-03-09T10:20:42.0780621Z","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger","thread_name":"main","message":"\r\n\r\nError starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled."}
{"@timestamp":"2025-03-09T10:20:42.1131224Z","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","message":"Application run failed"}
{"@timestamp":"2025-03-09T10:20:42.1275024Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] to prepare test instance [backend.academy.bot.BotApplicationTests@8bac10b]"}
{"@timestamp":"2025-03-09T11:47:41.6981628Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T11:47:41.8479627Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"Starting BotApplicationTests using Java 23.0.2 with PID 13304 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T11:47:41.8479627Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T11:47:45.1148984Z","logger_name":"org.testcontainers.images.PullPolicy","thread_name":"main","message":"Image pull policy will be performed by: DefaultPullPolicy()"}
{"@timestamp":"2025-03-09T11:47:45.1306747Z","logger_name":"org.testcontainers.utility.ImageNameSubstitutor","thread_name":"main","message":"Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')"}
{"@timestamp":"2025-03-09T11:47:45.2403559Z","logger_name":"org.testcontainers.DockerClientFactory","thread_name":"main","message":"Testcontainers version: 1.20.4"}
{"@timestamp":"2025-03-09T11:47:45.7981757Z","logger_name":"org.testcontainers.dockerclient.DockerMachineClientProviderStrategy","thread_name":"main","message":"docker-machine executable was not found on PATH ([C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common, C:\\ProgramData\\Oracle\\Java\\javapath, C:\\WINDOWS\\system32, C:\\WINDOWS, C:\\WINDOWS\\System32\\Wbem, C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\, C:\\WINDOWS\\System32\\OpenSSH\\, C:\\Program Files\\dotnet\\, C:\\Program Files (x86)\\dotnet\\, C:\\Program Files\\Git\\cmd, C:\\Program Files (x86)\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\DTS\\Binn\\, C:\\Program Files\\Docker\\Docker\\resources\\bin, C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\, C:\\Program Files\\CMake\\bin, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\, C:\\Users\\Andrew\\AppData\\Local\\Microsoft\\WindowsApps, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Microsoft VS Code\\bin, C:\\msys64\\ucrt64\\bin, C:\\Users\\Andrew\\AppData\\Local\\GitHubDesktop\\bin, C:\\Users\\Andrew\\.dotnet\\tools])"}
{"@timestamp":"2025-03-09T11:47:45.7981757Z","logger_name":"org.testcontainers.dockerclient.DockerClientProviderStrategy","thread_name":"main","message":"Could not find a valid Docker environment. Please check configuration. Attempted configurations were:\nAs no valid configuration was found, execution cannot continue.\nSee https://java.testcontainers.org/on_failure.html for more details."}
{"@timestamp":"2025-03-09T11:47:45.7981757Z","logger_name":"org.springframework.web.context.support.GenericWebApplicationContext","thread_name":"main","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Error creating bean with name 'redisContainer' defined in class path resource [backend/academy/bot/TestcontainersConfiguration.class]: Could not find a valid Docker environment. Please see logs and check configuration"}
{"@timestamp":"2025-03-09T11:47:45.8620463Z","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger","thread_name":"main","message":"\r\n\r\nError starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled."}
{"@timestamp":"2025-03-09T11:47:45.9073208Z","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","message":"Application run failed"}
{"@timestamp":"2025-03-09T11:47:45.9073208Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] to prepare test instance [backend.academy.bot.BotApplicationTests@5973e4ec]"}
{"@timestamp":"2025-03-09T11:52:36.9260949Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T11:52:37.1921364Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"Starting BotApplicationTests using Java 23.0.2 with PID 1640 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T11:52:37.1991806Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T11:52:44.6539426Z","logger_name":"org.testcontainers.images.PullPolicy","thread_name":"main","message":"Image pull policy will be performed by: DefaultPullPolicy()"}
{"@timestamp":"2025-03-09T11:52:44.6612815Z","logger_name":"org.testcontainers.utility.ImageNameSubstitutor","thread_name":"main","message":"Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')"}
{"@timestamp":"2025-03-09T11:52:44.8928742Z","logger_name":"org.testcontainers.DockerClientFactory","thread_name":"main","message":"Testcontainers version: 1.20.4"}
{"@timestamp":"2025-03-09T11:52:46.3603515Z","logger_name":"org.testcontainers.dockerclient.DockerMachineClientProviderStrategy","thread_name":"main","message":"docker-machine executable was not found on PATH ([C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common, C:\\ProgramData\\Oracle\\Java\\javapath, C:\\WINDOWS\\system32, C:\\WINDOWS, C:\\WINDOWS\\System32\\Wbem, C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\, C:\\WINDOWS\\System32\\OpenSSH\\, C:\\Program Files\\dotnet\\, C:\\Program Files (x86)\\dotnet\\, C:\\Program Files\\Git\\cmd, C:\\Program Files (x86)\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\DTS\\Binn\\, C:\\Program Files\\Docker\\Docker\\resources\\bin, C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\, C:\\Program Files\\CMake\\bin, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\, C:\\Users\\Andrew\\AppData\\Local\\Microsoft\\WindowsApps, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Microsoft VS Code\\bin, C:\\msys64\\ucrt64\\bin, C:\\Users\\Andrew\\AppData\\Local\\GitHubDesktop\\bin, C:\\Users\\Andrew\\.dotnet\\tools])"}
{"@timestamp":"2025-03-09T11:52:46.3627629Z","logger_name":"org.testcontainers.dockerclient.DockerClientProviderStrategy","thread_name":"main","message":"Could not find a valid Docker environment. Please check configuration. Attempted configurations were:\nAs no valid configuration was found, execution cannot continue.\nSee https://java.testcontainers.org/on_failure.html for more details."}
{"@timestamp":"2025-03-09T11:52:46.3630767Z","logger_name":"org.springframework.web.context.support.GenericWebApplicationContext","thread_name":"main","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Error creating bean with name 'redisContainer' defined in class path resource [backend/academy/bot/TestcontainersConfiguration.class]: Could not find a valid Docker environment. Please see logs and check configuration"}
{"@timestamp":"2025-03-09T11:52:46.5042403Z","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger","thread_name":"main","message":"\r\n\r\nError starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled."}
{"@timestamp":"2025-03-09T11:52:46.6233449Z","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","message":"Application run failed"}
{"@timestamp":"2025-03-09T11:52:46.6616622Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] to prepare test instance [backend.academy.bot.BotApplicationTests@13ed9738]"}
{"@timestamp":"2025-03-09T12:21:44.2842524Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T12:21:44.4133185Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"Starting BotApplicationTests using Java 23.0.2 with PID 13716 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T12:21:44.4133185Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T12:21:47.7635731Z","logger_name":"org.testcontainers.images.PullPolicy","thread_name":"main","message":"Image pull policy will be performed by: DefaultPullPolicy()"}
{"@timestamp":"2025-03-09T12:21:47.7635731Z","logger_name":"org.testcontainers.utility.ImageNameSubstitutor","thread_name":"main","message":"Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')"}
{"@timestamp":"2025-03-09T12:21:47.8585445Z","logger_name":"org.testcontainers.DockerClientFactory","thread_name":"main","message":"Testcontainers version: 1.20.4"}
{"@timestamp":"2025-03-09T12:21:48.8066466Z","logger_name":"org.testcontainers.dockerclient.DockerMachineClientProviderStrategy","thread_name":"main","message":"docker-machine executable was not found on PATH ([C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common, C:\\ProgramData\\Oracle\\Java\\javapath, C:\\WINDOWS\\system32, C:\\WINDOWS, C:\\WINDOWS\\System32\\Wbem, C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\, C:\\WINDOWS\\System32\\OpenSSH\\, C:\\Program Files\\dotnet\\, C:\\Program Files (x86)\\dotnet\\, C:\\Program Files\\Git\\cmd, C:\\Program Files (x86)\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\DTS\\Binn\\, C:\\Program Files\\Docker\\Docker\\resources\\bin, C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\, C:\\Program Files\\CMake\\bin, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\, C:\\Users\\Andrew\\AppData\\Local\\Microsoft\\WindowsApps, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Microsoft VS Code\\bin, C:\\msys64\\ucrt64\\bin, C:\\Users\\Andrew\\AppData\\Local\\GitHubDesktop\\bin, C:\\Users\\Andrew\\.dotnet\\tools])"}
{"@timestamp":"2025-03-09T12:21:48.8066466Z","logger_name":"org.testcontainers.dockerclient.DockerClientProviderStrategy","thread_name":"main","message":"Could not find a valid Docker environment. Please check configuration. Attempted configurations were:\nAs no valid configuration was found, execution cannot continue.\nSee https://java.testcontainers.org/on_failure.html for more details."}
{"@timestamp":"2025-03-09T12:21:48.8066466Z","logger_name":"org.springframework.web.context.support.GenericWebApplicationContext","thread_name":"main","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Error creating bean with name 'redisContainer' defined in class path resource [backend/academy/bot/TestcontainersConfiguration.class]: Could not find a valid Docker environment. Please see logs and check configuration"}
{"@timestamp":"2025-03-09T12:21:48.8693969Z","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger","thread_name":"main","message":"\r\n\r\nError starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled."}
{"@timestamp":"2025-03-09T12:21:48.8997718Z","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","message":"Application run failed"}
{"@timestamp":"2025-03-09T12:21:48.8997718Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] to prepare test instance [backend.academy.bot.BotApplicationTests@17c3a3]"}
{"@timestamp":"2025-03-09T12:26:24.6256424Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T12:26:24.8578641Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"Starting BotApplicationTests using Java 23.0.2 with PID 1108 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T12:26:24.8583665Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T12:26:31.2141461Z","logger_name":"org.testcontainers.images.PullPolicy","thread_name":"main","message":"Image pull policy will be performed by: DefaultPullPolicy()"}
{"@timestamp":"2025-03-09T12:26:31.2238347Z","logger_name":"org.testcontainers.utility.ImageNameSubstitutor","thread_name":"main","message":"Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')"}
{"@timestamp":"2025-03-09T12:26:31.4446866Z","logger_name":"org.testcontainers.DockerClientFactory","thread_name":"main","message":"Testcontainers version: 1.20.4"}
{"@timestamp":"2025-03-09T12:26:32.9224607Z","logger_name":"org.testcontainers.dockerclient.DockerMachineClientProviderStrategy","thread_name":"main","message":"docker-machine executable was not found on PATH ([C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common, C:\\ProgramData\\Oracle\\Java\\javapath, C:\\WINDOWS\\system32, C:\\WINDOWS, C:\\WINDOWS\\System32\\Wbem, C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\, C:\\WINDOWS\\System32\\OpenSSH\\, C:\\Program Files\\dotnet\\, C:\\Program Files (x86)\\dotnet\\, C:\\Program Files\\Git\\cmd, C:\\Program Files (x86)\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\DTS\\Binn\\, C:\\Program Files\\Docker\\Docker\\resources\\bin, C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\, C:\\Program Files\\CMake\\bin, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\, C:\\Users\\Andrew\\AppData\\Local\\Microsoft\\WindowsApps, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Microsoft VS Code\\bin, C:\\msys64\\ucrt64\\bin, C:\\Users\\Andrew\\AppData\\Local\\GitHubDesktop\\bin, C:\\Users\\Andrew\\.dotnet\\tools])"}
{"@timestamp":"2025-03-09T12:26:32.9239717Z","logger_name":"org.testcontainers.dockerclient.DockerClientProviderStrategy","thread_name":"main","message":"Could not find a valid Docker environment. Please check configuration. Attempted configurations were:\nAs no valid configuration was found, execution cannot continue.\nSee https://java.testcontainers.org/on_failure.html for more details."}
{"@timestamp":"2025-03-09T12:26:32.9278083Z","logger_name":"org.springframework.web.context.support.GenericWebApplicationContext","thread_name":"main","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Error creating bean with name 'redisContainer' defined in class path resource [backend/academy/bot/TestcontainersConfiguration.class]: Could not find a valid Docker environment. Please see logs and check configuration"}
{"@timestamp":"2025-03-09T12:26:33.0545048Z","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger","thread_name":"main","message":"\r\n\r\nError starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled."}
{"@timestamp":"2025-03-09T12:26:33.1365386Z","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","message":"Application run failed"}
{"@timestamp":"2025-03-09T12:26:33.1619027Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] to prepare test instance [backend.academy.bot.BotApplicationTests@355c236b]"}
{"@timestamp":"2025-03-09T12:35:03.229776Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T12:35:03.6536755Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"Starting BotApplicationTests using Java 23.0.2 with PID 13920 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T12:35:03.664898Z","logger_name":"backend.academy.bot.BotApplicationTests","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T12:35:11.1013497Z","logger_name":"org.testcontainers.images.PullPolicy","thread_name":"main","message":"Image pull policy will be performed by: DefaultPullPolicy()"}
{"@timestamp":"2025-03-09T12:35:11.1143348Z","logger_name":"org.testcontainers.utility.ImageNameSubstitutor","thread_name":"main","message":"Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')"}
{"@timestamp":"2025-03-09T12:35:11.3791171Z","logger_name":"org.testcontainers.DockerClientFactory","thread_name":"main","message":"Testcontainers version: 1.20.4"}
{"@timestamp":"2025-03-09T12:35:12.7965454Z","logger_name":"org.testcontainers.dockerclient.DockerMachineClientProviderStrategy","thread_name":"main","message":"docker-machine executable was not found on PATH ([C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common, C:\\ProgramData\\Oracle\\Java\\javapath, C:\\WINDOWS\\system32, C:\\WINDOWS, C:\\WINDOWS\\System32\\Wbem, C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\, C:\\WINDOWS\\System32\\OpenSSH\\, C:\\Program Files\\dotnet\\, C:\\Program Files (x86)\\dotnet\\, C:\\Program Files\\Git\\cmd, C:\\Program Files (x86)\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\, C:\\Program Files\\Microsoft SQL Server\\160\\DTS\\Binn\\, C:\\Program Files\\Docker\\Docker\\resources\\bin, C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\, C:\\Program Files\\CMake\\bin, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Python\\Python39\\, C:\\Users\\Andrew\\AppData\\Local\\Microsoft\\WindowsApps, C:\\Users\\Andrew\\AppData\\Local\\Programs\\Microsoft VS Code\\bin, C:\\msys64\\ucrt64\\bin, C:\\Users\\Andrew\\AppData\\Local\\GitHubDesktop\\bin, C:\\Users\\Andrew\\.dotnet\\tools])"}
{"@timestamp":"2025-03-09T12:35:12.7995465Z","logger_name":"org.testcontainers.dockerclient.DockerClientProviderStrategy","thread_name":"main","message":"Could not find a valid Docker environment. Please check configuration. Attempted configurations were:\nAs no valid configuration was found, execution cannot continue.\nSee https://java.testcontainers.org/on_failure.html for more details."}
{"@timestamp":"2025-03-09T12:35:12.8015489Z","logger_name":"org.springframework.web.context.support.GenericWebApplicationContext","thread_name":"main","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Error creating bean with name 'redisContainer' defined in class path resource [backend/academy/bot/TestcontainersConfiguration.class]: Could not find a valid Docker environment. Please see logs and check configuration"}
{"@timestamp":"2025-03-09T12:35:12.9507311Z","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger","thread_name":"main","message":"\r\n\r\nError starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled."}
{"@timestamp":"2025-03-09T12:35:13.0816194Z","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","message":"Application run failed"}
{"@timestamp":"2025-03-09T12:35:13.1145092Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] to prepare test instance [backend.academy.bot.BotApplicationTests@41854000]"}
{"@timestamp":"2025-03-09T14:55:46.6826459Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T14:55:46.8590367Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Starting ScrapperClientTest using Java 23.0.2 with PID 11204 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T14:55:46.8610595Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T14:55:52.9647283Z","logger_name":"org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver","thread_name":"main","message":"Exposing 1 endpoint beneath base path '/actuator'"}
{"@timestamp":"2025-03-09T14:55:53.0996406Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Started ScrapperClientTest in 7.993 seconds (process running for 14.709)"}
{"@timestamp":"2025-03-09T14:55:53.3523904Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener] to prepare test instance [backend.academy.bot.ScrapperClientTest@f3a3d22]"}
{"@timestamp":"2025-03-09T15:01:08.9429717Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T15:01:09.083085Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Starting ScrapperClientTest using Java 23.0.2 with PID 960 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T15:01:09.0860777Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T15:01:15.4672272Z","logger_name":"org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver","thread_name":"main","message":"Exposing 1 endpoint beneath base path '/actuator'"}
{"@timestamp":"2025-03-09T15:01:15.5663395Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Started ScrapperClientTest in 7.98 seconds (process running for 14.712)"}
{"@timestamp":"2025-03-09T15:01:15.7382695Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener] to prepare test instance [backend.academy.bot.ScrapperClientTest@485d79ef]"}
{"@timestamp":"2025-03-09T15:04:11.1233431Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T15:04:11.2624391Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Starting ScrapperClientTest using Java 23.0.2 with PID 4996 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T15:04:11.2695333Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T15:04:18.0826421Z","logger_name":"org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver","thread_name":"main","message":"Exposing 1 endpoint beneath base path '/actuator'"}
{"@timestamp":"2025-03-09T15:04:18.1875395Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Started ScrapperClientTest in 10.365 seconds (process running for 21.233)"}
{"@timestamp":"2025-03-09T15:04:18.3517348Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener] to prepare test instance [backend.academy.bot.ScrapperClientTest@37db2c4e]"}
{"@timestamp":"2025-03-09T15:08:11.335166Z","logger_name":"org.hibernate.validator.internal.util.Version","thread_name":"background-preinit","message":"HV000001: Hibernate Validator 8.0.2.Final"}
{"@timestamp":"2025-03-09T15:08:11.4962966Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Starting ScrapperClientTest using Java 23.0.2 with PID 5984 (started by Andrew in C:\\Users\\Andrew\\.ssh\\java-TheOriginalMJKey\\bot)"}
{"@timestamp":"2025-03-09T15:08:11.4991376Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"No active profile set, falling back to 1 default profile: \"default\""}
{"@timestamp":"2025-03-09T15:08:20.1249515Z","logger_name":"org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver","thread_name":"main","message":"Exposing 1 endpoint beneath base path '/actuator'"}
{"@timestamp":"2025-03-09T15:08:20.2591085Z","logger_name":"backend.academy.bot.ScrapperClientTest","thread_name":"main","message":"Started ScrapperClientTest in 10.642 seconds (process running for 16.696)"}
{"@timestamp":"2025-03-09T15:08:20.5476958Z","logger_name":"org.springframework.test.context.TestContextManager","thread_name":"main","message":"Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener] to prepare test instance [backend.academy.bot.ScrapperClientTest@684682e4]"}
